### ISSUE TITLE
Add support for the DNS interface

### ISSUE THREAD

**Issue by adulau** [hashlookup/PyHashlookup#1]
Add support for the DNS interface

**Comment by Rafiot** [comment]
is there a difference on the result? In which context do we want to use the DNS interface vs. the REST one? When using a python module I mean.

**Comment by adulau** [comment]
It only works with single query and the results don't contain the complete details of the file (such as the source).

Some people might want to use the DNS when the HTTP interface is not accessible or they want to benefit from DNS caching. It's more a fall-back to standard ReST.

**Comment by Rafiot** [comment]
So with DNS, I seem to randomly get no answer (with either dig or dnspython), but the tests seem to be passing (at least locally). But it might be my cache being inconsistent or something, so I'll close for now.
